version: 0.0
os: linux

files:
  - source: /stfc
    destination: /opt/stfc/
  - source: /config.toml
    destination: /opt/stfc/

hooks:
  BeforeInstall:
    - location: scripts/BeforeInstall.sh
      timeout: 300
  AfterInstall:
    - location: scripts/AfterInstall.sh
      timeout: 300
