version: 0.2

phases:
  install:
    runtime-versions:
      golang: 1.x
    commands:
      - echo "Installing dependencies..."
      - go mod download

  build:
    commands:
      - echo "Building the application..."
      - go build -o stfc main.go

  post_build:
    commands:
      - echo "Build completed successfully."
      - echo "Preparing files for deployment..."

artifacts:
  files:
    - stfc
    - config.toml
    - appspec.yml
    - scripts/** 
  discard-paths: no
